version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    tty: true
    environment:
      - TZ=Japan
    volumes:
      - .:/go/src/github.com/ren-kt/uranai_api
    ports:
      - 8080:8080
